### ISSUE TITLE
Integration of mir.stat.distribution with mir-random

### ISSUE THREAD

**Issue by jmh530** [libmir/mir-stat#47]
My thinking is that it would be good to provide an API for calling mir-random through mir.stat.distribution so that things are consistent, e.g. normalRand would be like a call with normalVariable and randSlice in mir-random.

One interesting thing is that normalVariable is a struct to represent the distribution, whereas the API for mir.stat.distribution uses function parameters. So one question would be whether it makes sense to offer a similar struct-based representation of the distributions that would be similar to what is in mir-random. And any preference on what that looks like.

**Comment by 9il** [comment]
That works well only for simple distributions. For more complex cases like GIG that doesn't work well because representation used for random number generation is likely different comparing to a parameter set used for CDF. Another issue is a different representations for parameter sets. For a random generation likely only one is used, while for CDF different representations may assume different implementations.

Also, random vars and CDFs are used in different places. Likely one need either CDF or a random variable (for a after research production stage).

mir-stat is already have a heavy ontology that gets more space then math logic for simple distributions.

I would argue to do not add additional ontology complexity for code that doesn't actualy share common logic.

**Comment by jmh530** [comment]
@9il Thanks for the detailed reply.

One argument I would generally make about distributions is that you can have a simple set of distributions that build up into arbitrarily complex distributions that don't have a specific name. So from my perspective, being able to work with some common set of distributions is more important than all distributions. 

I'll grant your argument about ontology and struct-based representation of the distributions, but I was also thinking something similar to below (in the simplest case) for something like `normalRand`. Would you also be opposed to including something like this in `mir-stat`?

```d
static if (__traits(compiles, { import mir.random; })) {
    import mir.random.variable: normalVar;
    import mir.random.algorithm: randomSlice;
    auto normalRand(ulong[2] n, double mu, double stdDev) {
     	return normalVar(mu, stdDev).randomSlice(n[0], n[1]);   
    }
    auto normalRand(ulong n, double mu, double stdDev) {
     	return normalVar(mu, stdDev).randomSlice(n);   
    }
    auto normalRand(ulong[2] n) {
     	return normalVar.randomSlice(n[0], n[1]);   
    }
    auto normalRand(ulong n) {
     	return normalVar.randomSlice(n);   
    }
}
```

**Comment by 9il** [comment]
I would recommend to keep random code and API smaller and in mir-random. We do have [numir's normal](https://libmir.github.io/numir/random.html#normal) wrapper already.

I understand why that maybe usefull for daily research. But for production code it isn't good. D isn't popular and unlikely we do have resources to maintain both kinds of API. I am afraid it maybe a problem to maintain existing API after a while.

**Comment by jmh530** [comment]
Sounds good.
